debug reflector script

diff --git a/run_once_before_B_install_dependencies.sh.tmpl b/run_once_before_B_install_dependencies.sh.tmpl
--- a/run_once_before_B_install_dependencies.sh.tmpl
+++ b/run_once_before_B_install_dependencies.sh.tmpl
@@ -1,18 +1,8 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
 # First script to be run after "chezmoi init --apply"
-# Installs pre-opporational packages.
-
-
-# Function to check if reflector is installed
-check_reflector() {
-    if ! command -v reflector &> /dev/null; then
-        sudo pacman -S reflector
-        echo "reflector installed"
-    else
-        echo "reflector is already installed"
-    fi
-}
+# Updates system packages, installs dependencies for Ansible,
+# and configures download mirrors using Reflector.
 
 # Function to copy files if reflector is installed
 copy_files() {
@@ -21,8 +11,27 @@ copy_files() {
     else
         echo "Installing Reflector service and timer files."
         sudo cp {{ .chezmoi.sourceDir }}/Development/ansible/arch_config/resources/files/reflector.service /etc/systemd/system/
-        sudo cp {{ .chezmoi.sourceDir }}/Development/ansible/arch_config/resources/files/flector.timer /etc/systemd/system/
+        sudo cp {{ .chezmoi.sourceDir }}/Development/ansible/arch_config/resources/files/reflector.timer /etc/systemd/system/
         
+    fi
+}
+
+# Function to check if reflector is installed
+check_reflector() {
+    if ! command -v reflector &> /dev/null; then
+        sudo pacman -S reflector
+        echo "reflector installed"
+
+        copy_files
+    else
+        echo "reflector is already installed"
+    fi
+    
+    if ! systemctl is-active --quiet reflector.timer; then
+        echo "reflector.timer is not running. Starting it..."
+        start_reflector
+    else
+        echo "reflector.timer is already running."
     fi
 }
 
@@ -33,46 +42,46 @@ start_reflector() {
     echo "Mirrorlist updated and timer set for weekly"
 }
 
+update_system(){
+    sudo pacman -Syu
+}
+
+
+install_dependencies(){
+    # Install "age" Encryption tool
+    if ! [[ $(command -v age) ]];
+    then
+        echo "Installing package 'age' encryption tool..."
+
+        sudo pacman -S age
+
+        echo "age package installed"
+    fi
+
+    # Install "Ansible" Automation tool
+    if ! [[ $(command -v ansible) ]];
+    then
+        sudo pacman -S ansible
+
+        echo "Ansible Installed"
+    fi
+
+    # Install Ansible's "community.general" Collection
+    # Check if the community.general collection is installed
+    ansible-galaxy collection list | grep -q 'community.general'
+
+    # Check the exit status of the grep command
+    if [ $? -ne 0 ]; then
+        # Install the collection if it is not found
+        ansible-galaxy collection install community.general --force
+        echo "Ansible community.general installed."
+    else
+        echo "Ansible community.general is already installed."
+    fi
+}
+
+
 # Main script
 check_reflector
-copy_files
-
-if ! systemctl is-active --quiet reflector.timer; then
-    echo "reflector.timer is not running. Starting it..."
-    start_reflector
-else
-    echo "reflector.timer is already running."
-fi
-
-
-sudo pacman -Syu
-
-
-
-if ! [[ $(command -v age) ]];
-then
-    echo "Installing package 'age' encryption tool..."
-
-    sudo pacman -S age
-
-    echo "age package installed"
-fi
-
-if ! [[ $(command -v ansible) ]];
-then
-    sudo pacman -S ansible
-
-    echo "Ansible Installed"
-fi
-
-# Check if the community.general collection is installed
-ansible-galaxy collection list | grep -q 'community.general'
-
-# Check the exit status of the grep command
-if [ $? -ne 0 ]; then
-    # Install the collection if it is not found
-    ansible-galaxy collection install community.general --force
-    echo "Ansible community.general installed."
-else
-    echo "Ansible community.general is already installed."
-fi
+update_system
+install_dependencies
